apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: guacamole-db-secrets
  annotations:
    xlscsde.nhs.uk/secretUsage: "Guacamole DB Credentials"
spec:
  name: guacamole
  secrets:
  - from: GuacDbUsername
    to: db_username

  - from: GuacDbPassword
    to: db_password
---
apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: ${dns_prefix}guacamole.${private_dnz_zone}-tls
  annotations:
    xlscsde.nhs.uk/secretUsage: "Wildcard Certificate"
spec:
  name: ${dns_prefix}guacamole.${private_dnz_zone}-tls
  type: kubernetes.io/tls
  secrets:
  - from: WildcardCertificate
    to: tls.crt

  - from: WildcardCertificateKey
    to: tls.key