portal:
  ingress:
    host: ${environment_dns_prefix}guacamole${environment_dns_suffix}.${private_dnz_zone}
    tls:
      enabled: true
      secretName: ${environment_dns_prefix}guacamole${environment_dns_suffix}.${private_dnz_zone}-tls
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect : "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect : "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
      xlscsde.nhs.uk/dns-record: guacamole${environment_dns_suffix}

  volumeMounts:
  - name: guacamole-certificates
    mountPath: /etc/ssl/certs
    readOnly: true

  volumes:
  - name: guacamole-certificates
    configMap:
      name: guacamole-certificate-authority
      defaultMode: 0644
      
  env:
    - name: JAVA_OPTS
      value: "-Djavax.net.ssl.trustStore=\"/etc/ssl/certs/bundle.jks\" -Djavax.net.ssl.trustStorePassword=\"changeit\""
    - name: OPENID_AUTHORIZATION_ENDPOINT
      value: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/realms/lsc-sde/protocol/openid-connect/auth
    - name: OPENID_JWKS_ENDPOINT
      value: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/realms/lsc-sde/protocol/openid-connect/certs
    - name: OPENID_ISSUER
      value: https://${environment_dns_prefix}keycloak${environment_dns_suffix}.${private_dnz_zone}/realms/lsc-sde
    - name: OPENID_CLIENT_ID
      value: guacamole
    - name: OPENID_REDIRECT_URI
      value: "https://${environment_dns_prefix}guacamole${environment_dns_suffix}.${private_dnz_zone}/guacamole/"
    - name: EXTENSION_PRIORITY
      value: "openid"
    - name: OPENID_SCOPE
      value: "openid email realm_groups profile"
    - name: OPENID_USERNAME_CLAIM_TYPE 
      value: workspace_id
    - name: USE_SYSTEM_CA_CERTS
      value: "true"

database:
  type: postgres
  hostname: "${postgresql_server}"
  port: "5432"
  database: "guacamole"
  user: "guacamole@${postgresql_server}"
  password:
    secret: "guacamole"
    key: "db-password"