apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: guacamole
  namespace: ${guacamole_namespace}
  annotations:
    xlscsde.nhs.uk/flux-branch: ${guacamole_branch}
spec:
  targetNamespace: ${guacamole_namespace}
  releaseName: guacamole
  chart:
    spec:
      chart: guacamole
      version: ${guacamole_chart_version}
      sourceRef:
        kind: HelmRepository
        name: guacamole
        namespace: ${guacamole_namespace}
  interval: 5m0s
  install:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true
  upgrade:
    remediation:
      retries: -1
    disableWait: true
    disableWaitForJobs: true