apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: ${environment_dns_prefix}guacamole${environment_dns_suffix}.${private_dnz_zone}-tls
  annotations:
    xlscsde.nhs.uk/secretUsage: "Wildcard Certificate"
spec:
  name: ${environment_dns_prefix}guacamole${environment_dns_suffix}.${private_dnz_zone}-tls
  type: kubernetes.io/tls
  secrets:
  - from: WildcardCertificate
    to: tls.crt
    
  - from: WildcardCertificateKey
    to: tls.key
---
apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: guacamole
  annotations:
    xlscsde.nhs.uk/secretUsage: "Guacamole passwords"
spec:
  name: guacamole
  secrets:
  - from: GuacDbPassword
    to: db-password