portal:
  ingress:
    host: guacamole.xlscsde.local
    tls:
      enabled: true
      secretName: example-tls-secret
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect : "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect : "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
      nginx.ingress.kubernetes.io/app-root: /guacamole 


  volumeMounts:
  - name: guacamole-certificates
    mountPath: /etc/ssl/certs
    readOnly: true

  volumes:
  - name: guacamole-certificates
    configMap:
      name: xlscsde-local-bundle
      defaultMode: 0644
  
  env:
    - name: JAVA_OPTS
      value: "-Djavax.net.ssl.trustStore=\"/etc/ssl/certs/bundle.jks\" -Djavax.net.ssl.trustStorePassword=\"changeit\""
    - name: OPENID_AUTHORIZATION_ENDPOINT
      value: https://keycloak.xlscsde.local/realms/lsc-sde/protocol/openid-connect/auth
    - name: OPENID_JWKS_ENDPOINT
      value: https://keycloak.xlscsde.local/realms/lsc-sde/protocol/openid-connect/certs
    - name: OPENID_ISSUER
      value: https://keycloak.xlscsde.local/realms/lsc-sde
    - name: OPENID_CLIENT_ID
      value: guacamole
    - name: OPENID_REDIRECT_URI
      value: "https://guacamole.xlscsde.local"
    - name: EXTENSION_PRIORITY
      value: "openid"
    - name: OPENID_SCOPE
      value: "openid email realm_groups profile"
    - name: OPENID_USERNAME_CLAIM_TYPE 
      value: workspace_id
    - name: USE_SYSTEM_CA_CERTS
      value: "true"
database:
  type: postgres
  hostname: "${PG_FQDN}"
  port: "5432"
  database: "guacamole"
  user: "guacamole"
  password:
    secret: "guacamole"
    key: "db-password"