apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: guacamole-certificate-authority  
spec:
  sources:
  - useDefaultCAs: false

  - secret:
      name: "guacamole-certificate-authority-tls"
      key: "tls.crt"

  - configMap:
      name: nhs-certificates
      key: root-nwsis-ca.crt
      
  - configMap:
      name: nhs-certificates
      key: sub-lth-ca

  target:
    configMap:
      key: "ca-certificates.crt"
    additionalFormats:
      jks:
        key: "bundle.jks"
      pkcs12:
        key: "bundle.p12"

    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: ${guacamole_namespace}
        