apiVersion: xlscsde.nhs.uk/v1
kind: SecretsDistribution
metadata:
  name: xlscsde-enterprise-certificate
  annotations:
    xlscsde.nhs.uk/secretUsage: ""
spec:
  name: xlscsde-enterprise-certificate
  secrets:
  - from: CertificateAuthority
    to: ca.crt
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: xlscsde-enterprise-certificate
spec:
  sources:
  - secret:
      name: xlscsde-enterprise-certificate
      key: ca.crt
  target:
    configMap:
      key: "enterprise.crt" 
    additionalFormats:
      jks:
        key: "enterprise.jks"
      pkcs12:
        key: "enterprise.p12"
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: ${guacamole_namespace}